thefirstapp/urls.py
__author__ = 'ccaf'

from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$',views.default_return),
    url(r'(?P<pk>\d+)/$',views.user_view)
]

thefirstone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^neeraj/', views.neeraj_return),
    url(r'^thefirstapp/', include('thefirstapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.default_return)
]

thefirstapp/models.py
from django.db import models

# Create your models here.

class Appnames(models.Model):
    is_played=models.DateTimeField(auto_now_add=True)
    app_name=models.CharField(max_length=255)
    app_type=models.TextField()

    def __str__(self):
        return(self.app_name)

class Howtouse(models.Model):
    step_title=models.CharField(max_length=255)
    step1=models.TextField()
    step2=models.TextField()
    step3=models.TextField()
    order=models.IntegerField(default=0)
    app_name=models.ForeignKey(Appnames)

    def __str__(self):
        return (self.step_title)

thefirstapp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

from .models import Appnames

def default_return(request):
#   return HttpResponse(', '.join(str(name) for name in Appnames.objects.all()))
    names_to_return=Appnames.objects.all()
    return render(request,'thefirstapp/app_frontend.html',{'name_of_apps': names_to_return})

def user_view(request,pk):
    app_details=Appnames.objects.get(pk=pk)
    return render(request,'thefirstapp/detailedview.html',{'appvar': app_details})

thefirstone/views.py
from django.shortcuts import render

def default_return(request):
    return render(request,"homepage.html")

def neeraj_return(request):
    return render(request,"neeraj.html")

templates/homepage.html
{% extends 'template.html' %}

{% block title_block %} Django is cool {% endblock %}
{% block body_block %} Django is very cool {% endblock %}

templates/template.html
<html>
<head>
    <title> {% block title_block %} {% endblock %}</title>
</head>
<body>
<h1>
    {% block body_block %} {% endblock %}
</h1>

</body>
</html>

thefirstapp/templates/thefirstapp/app_frontend.html
{% for name in name_of_apps %}
    <h2>{{ name.app_name }}</h2>
    {{ name.app_type }}
{% endfor %}

thefirstapp/templates/thefirstapp/detailedview.html
<html>
<head>
    <title>{{ appvar.app_name }}</title>
</head>
<body>
    <h2>{{ appvar.app_name }}</h2>
    <h3>{{ appvar.app_type }}</h3>


{% for howtosteps in appvar.howtouse_set.all %}
    <h4>{{ howtosteps.step_title }}</h4>
    <h5>{{ howtosteps.step1 }}</h5>
    <h5>{{ howtosteps.step2 }}</h5>
    <h5>{{ howtosteps.step3 }}</h5>
{% endfor %}


</body>
</html>